### ISSUE TITLE
option for only allowing properly aligned paired reads

### ISSUE THREAD

**Issue by pcantalupo** [boratyng/magicblast#5]
Hi, I was wondering if MB has an option similar to HISAT2 `--no-mixed` and `--no-discordant`? I would be interested to see this in MB since the output generated would not have any single reads of a pair.

**Comment by boratyng** [comment]
At this point Magic-BLAST does not have these options. Sorry. We can add them in the next version. In the mean time, properly aligned convergent reads are indicated with the second bit set in SAM flags. So you can filter the output requiring that flag & 2 != 0.

What is the expected result for these options? If reads align discordantly, should they be reported as unaligned?

**Comment by boratyng** [comment]
In version 1.4.0 there is a `-no-discordant` option that reports only properly aligned pairs.
